use futures::stream;
use tokio_stream::StreamExt;

use super::types::*;

pub struct StubProvider;

impl StubProvider {
    pub fn new() -> Self {
        Self
    }

    pub async fn generate(&self, _request: &LlmRequest) -> Result<LlmResponse, LlmError> {
        let scenario = pick_stub(_request);
        Ok(LlmResponse {
            content: scenario.to_string(),
            prompt_tokens: 150,
            completion_tokens: 400,
            model: "stub-v1".into(),
        })
    }

    pub fn generate_stream(&self, request: &LlmRequest) -> StreamResult {
        let text = pick_stub(request).to_string();
        let words: Vec<String> = text.split_whitespace().map(|w| format!("{w} ")).collect();
        // ponytail: no sleep — instant delivery so stub never shows blank screen
        Box::pin(stream::iter(words).map(Ok))
    }
}

fn pick_stub(req: &LlmRequest) -> &'static str {
    let pool = country_pool(&req.context_json);
    let idx = req.user_prompt.len() % pool.len();
    pool[idx]
}

fn country_pool(context_json: &str) -> &'static [&'static str] {
    let country = serde_json::from_str::<serde_json::Value>(context_json)
        .ok()
        .and_then(|v| v["player_country"].as_str().map(|s| s.to_ascii_lowercase()));

    match country.as_deref() {
        Some("russia") => STUBS_RUSSIA,
        Some("china") => STUBS_CHINA,
        Some("unitedkingdom") | Some("france") => STUBS_EU,
        Some("india") | Some("pakistan") => STUBS_SOUTH_ASIA,
        Some("dprk") | Some("northkorea") => STUBS_DPRK,
        _ => STUBS, // USA, NATO allies, unknown → default
    }
}

const STUBS_RUSSIA: &[&str] = &[
    r#"{"title":"АРКТИЧЕСКИЙ РУБЕЖ","description":"СИТДОН: Норвежский фрегат нарушил северную границу ИЭЗ России вблизи архипелага Шпицберген. Американский разведчик RC-135 барражирует вдоль Кольского полуострова.\n\nОЦЕНКА РАЗВЕДКИ: Характер действий NATO указывает на рекогносцировку Северного флота. Береговая оборона доложила о контактах неизвестных подводных лодок у Гаджиево.","threat_level":"High","affected_regions":["Баренцево море","Шпицберген","Кольский полуостров","Норвежское море"],"player_options":[{"id":1,"label":"Поднять авиацию ПВО","description":"Вывести Су-35 на перехват RC-135 — демонстрация силы, риск воздушного инцидента"},{"id":2,"label":"Дипломатическая нота","description":"Официальный протест посольству Норвегии — медленно, но в правовом поле"},{"id":3,"label":"Усилить ПЛО","description":"Выдвинуть противолодочные корабли — защищает базы, не даёт повода для эскалации"},{"id":4,"label":"Переговоры через канал Россия–НАТО","description":"Задействовать официальный канал — сохраняет диалог, риск утечки намерений"}],"comms":[{"origin":"NATO","native_text":"SACEUR FLASH: Exercise ARCTIC SHIELD enters final phase. Norwegian vessel conducting freedom of navigation per international law.","english_translation":"Главнокомандующий НАТО ФЛЭШ: Учение ARCTIC SHIELD — финальная фаза. Норвежское судно действует в рамках свободы судоходства.","priority":"Flash"},{"origin":"Россия","native_text":"Штаб Северного флота: обнаружена подводная цель в квадрате 47-Д. Силам ПЛО приступить к слежению.","english_translation":"Northern Fleet HQ: subsurface contact detected in grid 47-D. ASW units commence tracking.","priority":"Immediate"}]}"#,

    r#"{"title":"ВНУТРЕННИЙ ПЕРИМЕТР","description":"СИТДОН: Серия скоординированных протестов охватила восемь городов после ареста оппозиционного блогера. Западные НКО предположительно финансируют организаторов. Зафиксирована активность иностранных спецслужб через дипломатические каналы в Москве.\n\nОЦЕНКА ФСБ: Операция соответствует схеме «управляемой нестабильности», применявшейся в Сербии (2000), Грузии (2003) и Украине (2014).","threat_level":"Medium","affected_regions":["Москва","Санкт-Петербург","Новосибирск","Екатеринбург"],"player_options":[{"id":1,"label":"Закрыть НКО","description":"Признать иностранные НКО нежелательными — решительно, но ухудшает отношения с Западом"},{"id":2,"label":"Переговоры с умеренной оппозицией","description":"Частичный диалог — снижает напряжённость, риск сигнала о слабости"},{"id":3,"label":"Информационная операция","description":"Государственные СМИ публикуют доказательства иностранного вмешательства"},{"id":4,"label":"Усиление силовых структур","description":"Превентивное развёртывание — показывает решимость, риск инцидентов"}],"comms":[{"origin":"США","native_text":"State Dept: We call on Russian authorities to respect the right of peaceful assembly and release detained civil society leaders.","english_translation":"Госдепартамент: Призываем уважать право на мирные собрания и освободить задержанных.","priority":"Priority"},{"origin":"ФСБ","native_text":"ФСБ России: Установлена связь координаторов протестов с сотрудниками посольства США. Материалы переданы в Генеральную прокуратуру.","english_translation":"FSB: Links established between protest coordinators and US Embassy personnel. Materials transferred to Prosecutor General.","priority":"Immediate"}]}"#,
];

const STUBS_CHINA: &[&str] = &[
    r#"{"title":"台湾海峡危机","description":"战情简报：美国海军航母打击群进入台湾海峡实施所谓「航行自由」行动，与台湾海军进行联合演习。美国国会代表团宣布新一轮对台军售计划。\n\n情报评估：此次挑衅系近年最严重的主权侵犯行为。解放军东部战区已提升至二级战备。火箭军已部署东风-26至沿海阵地。","threat_level":"Critical","affected_regions":["台湾海峡","东海","冲绳","菲律宾海"],"player_options":[{"id":1,"label":"海上封锁演习","description":"在台湾海峡实施模拟封锁演习——展示能力，对美形成强大威慑"},{"id":2,"label":"外交警告","description":"召见美国大使提出强烈抗议，发表严正声明"},{"id":3,"label":"暂停军事热线","description":"中止与美军的直接沟通渠道——强烈信号，但增加误判风险"},{"id":4,"label":"升级战备等级","description":"宣布提升全军战备——展示决心，需谨慎管控升级节奏"}],"comms":[{"origin":"美国","native_text":"PACOM: USS carrier CSG conducting lawful FONOP in the Taiwan Strait per international law.","english_translation":"太平洋司令部：航母打击群在台湾海峡依据国际法实施合法航行自由行动。","priority":"Flash"},{"origin":"中央军委","native_text":"中央军事委员会通令：东部战区进入二级战备，各部队立即进入预定阵地，等待下一步命令。","english_translation":"CMC Order: Eastern Theater Command raised to Level-2 readiness. All units move to assigned positions and await further orders.","priority":"Flash"}]}"#,

    r#"{"title":"南海主权","description":"战情简报：菲律宾海警船在美国舰艇护送下向仁爱礁运送违禁建筑材料。越南同期在西沙群岛实施扩建工程。美国舰艇在南海实施密集的所谓「航行自由」行动。\n\n情报评估：美国系统性支持周边国家蚕食南海主权。九段线内所有海域均属中国固有领土。","threat_level":"High","affected_regions":["仁爱礁","西沙群岛","南海","苏比克湾"],"player_options":[{"id":1,"label":"海警驱离行动","description":"拦截驱离菲律宾运补船——坚定维权，控制行动烈度"},{"id":2,"label":"水炮警告","description":"使用水炮驱散侵权船只——有效但国际舆论压力较大"},{"id":3,"label":"双边谈判","description":"通过外交渠道与马尼拉直接沟通"},{"id":4,"label":"媒体反制","description":"发布菲律宾侵权完整证据链——争夺话语权"}],"comms":[{"origin":"菲律宾","native_text":"PCG: We assert our sovereign rights under UNCLOS in our EEZ. Our resupply mission is a legitimate exercise of sovereignty.","english_translation":"菲律宾海警：依据《联合国海洋法公约》主张专属经济区主权权利。","priority":"Priority"},{"origin":"海警局","native_text":"中国海警局：已对侵入我主权海域的外国船只发出正式驱离警告，执法行动依法进行。","english_translation":"China Coast Guard: Formal expulsion warning issued to foreign vessels intruding into sovereign waters. Enforcement conducted according to law.","priority":"Immediate"}]}"#,
];

const STUBS_EU: &[&str] = &[
    r#"{"title":"CHANNEL SENTINEL","description":"SITREP: Unidentified submarine contact detected in the English Channel by HMS Trent. Contact matches acoustic signature of a Kilo-class diesel-electric submarine. French DGSE reports infiltration of Calais port infrastructure by signals intelligence assets.\n\nINTELLIGENCE ASSESSMENT: Submarine transiting outside declared exercise corridors. Critical undersea infrastructure — Channel Tunnel power cables and EuroConnect fiber links — may be at risk.","threat_level":"High","affected_regions":["English Channel","Strait of Dover","Calais","Dover"],"player_options":[{"id":1,"label":"Deploy Maritime Patrol","description":"Surface patrol to localise contact — visible deterrent, may cause submarine to dive deeper"},{"id":2,"label":"Franco-British ASW Exercise","description":"Activate bilateral response protocol — strong combined signal without unilateral escalation"},{"id":3,"label":"Notify NATO MARCOM","description":"Alert Allied Maritime Command — broader response, shares burden, slower reaction"},{"id":4,"label":"Infrastructure Lockdown","description":"Heighten security on Channel Tunnel and cable landing stations — defensive only"}],"comms":[{"origin":"France","native_text":"DGSE alerte: signatures électroniques détectées près des infrastructures portuaires de Calais. Présence d'actifs de renseignement étrangers confirmée.","english_translation":"DGSE alert: electronic signatures detected near Calais port infrastructure. Foreign intelligence assets confirmed.","priority":"Immediate"},{"origin":"UK","native_text":"NORTHWOOD HQ: Submerged contact classified HOSTILE SUBSURFACE. MPA Poseidon airborne from Lossiemouth.","english_translation":"NORTHWOOD HQ: Submerged contact classified HOSTILE SUBSURFACE. MPA Poseidon airborne from Lossiemouth.","priority":"Flash"}]}"#,

    r#"{"title":"OPERATION SERVAL II","description":"SITREP: Islamist insurgent forces overran the perimeter of Gao airbase in Mali, where 350 French and 120 British special forces advisors are deployed. Local FAMA units have broken contact. Evacuation helicopters are grounded by dust storm conditions. Weather window opens in 4 hours.\n\nINTELLIGENCE ASSESSMENT: Wagner Group-affiliated fighters observed among insurgent elements — coordinated effort to embarrass European presence in the Sahel.","threat_level":"Critical","affected_regions":["Gao","Mali","Sahel","Niger"],"player_options":[{"id":1,"label":"Rafale Close Air Support","description":"Call French CAS from forward base — effective but requires ROE expansion"},{"id":2,"label":"Hold Perimeter","description":"Defend airbase and wait for evacuation weather window — reduces casualties if perimeter holds"},{"id":3,"label":"Negotiate via Bamako","description":"Diplomatic route through Malian government — slow and unreliable given junta's Wagner ties"},{"id":4,"label":"Emergency Reinforcement","description":"Fly Parachute Regiment company from Chad — 2-hour lag, decisively changes force balance"}],"comms":[{"origin":"France","native_text":"Commandement des Opérations Spéciales: Position à Gao sous pression. Météo empêche évacuation. Demandons appui aérien immédiat.","english_translation":"Special Operations Command: Gao position under pressure. Weather prevents evacuation. Requesting immediate air support.","priority":"Flash"},{"origin":"UK","native_text":"PJHQ Northwood: British personnel at Gao accounted for. SAS QRF at 30 minutes notice from Ouagadougou.","english_translation":"PJHQ Northwood: British personnel at Gao accounted for. SAS QRF at 30 minutes notice from Ouagadougou.","priority":"Immediate"}]}"#,
];

const STUBS_SOUTH_ASIA: &[&str] = &[
    r#"{"title":"LINE OF CONTROL STANDOFF","description":"SITREP: Indian Army reports a Pakistani SSG infiltration team of approximately 30 personnel has crossed the LoC in Kupwara sector. Two Indian Army posts have been attacked. Pakistan has moved an armoured brigade to forward assembly areas near Sialkot.\n\nINTELLIGENCE ASSESSMENT: Infiltration exceeds typical militant pattern — state-directed action suspected. Pakistan's strategic nuclear forces have not altered posture, but ISPR has made ambiguous statements about 'full-spectrum deterrence.'","threat_level":"Critical","affected_regions":["Kashmir","Line of Control","Kupwara","Sialkot"],"player_options":[{"id":1,"label":"Surgical Strike Option","description":"Limited cross-LoC strike on launch pads — established doctrine but risks escalation to nuclear threshold"},{"id":2,"label":"DGMO Hotline","description":"Engage Pakistan Army directly through military hotline — preserves communication, signals restraint"},{"id":3,"label":"UN Security Council Briefing","description":"Internationalise the crisis — creates witnesses but limits freedom of action"},{"id":4,"label":"Forward Deployment Only","description":"Reinforce LoC without offensive action — shows resolve, buys time for diplomacy"}],"comms":[{"origin":"Pakistan","native_text":"ISPR Statement: Pakistan firmly denies any involvement in cross-LoC activity. India's provocative troop movements threaten regional stability. Strategic forces on full alert.","english_translation":"ISPR Statement: Pakistan denies LoC involvement. Indian movements threaten stability. Strategic forces on full alert.","priority":"Flash"},{"origin":"India","native_text":"INTEGRATED DEFENCE STAFF: LoC violation confirmed, Kupwara sector. Corps commander has authority to respond under established ROE. DGMO hotline activated.","english_translation":"IDS: LoC violation confirmed Kupwara. Corps ROE authority granted. DGMO hotline activated.","priority":"Immediate"}]}"#,

    r#"{"title":"INDUS WATERS CRISIS","description":"SITREP: India suspended the Indus Waters Treaty following the Pahalgam attack. Pakistan's agricultural heartland faces water scarcity as India redirects Chenab River flows for the Bursar Dam. Pakistan's NSC has convened an emergency session.\n\nINTELLIGENCE ASSESSMENT: Water treaty suspension is unprecedented since the 1960 agreement. Pakistan's wheat crop is critically dependent on Chenab irrigation. Pakistani military is lobbying for coercive options.","threat_level":"High","affected_regions":["Punjab (Pakistan)","Chenab River","Jammu","Lahore"],"player_options":[{"id":1,"label":"Restore Treaty Compliance","description":"Resume water flows — de-escalates crisis but surrenders leverage gained after Pahalgam"},{"id":2,"label":"World Bank Arbitration","description":"Invoke treaty dispute mechanism — legally grounded, multi-year process"},{"id":3,"label":"Conditional Offer","description":"Link water flows to Pakistan's action on militant infrastructure — high-leverage negotiation"},{"id":4,"label":"Maintain Suspension","description":"Continue pressure — maximum leverage but risks food crisis and military response"}],"comms":[{"origin":"Pakistan","native_text":"NSC Islamabad: India's suspension of the Indus Waters Treaty is an act of water warfare. Pakistan will exhaust all legal and other means to secure its water rights.","english_translation":"NSC Islamabad: IWT suspension is water warfare. Pakistan will use all means to secure water rights.","priority":"Flash"},{"origin":"India","native_text":"MEA New Delhi: Suspension of IWT is a sovereign decision pending Pakistan's verifiable action against designated terrorist organisations on its territory.","english_translation":"MEA: IWT suspension pending Pakistan action against designated terrorist organisations.","priority":"Priority"}]}"#,
];

const STUBS_DPRK: &[&str] = &[
    r#"{"title":"핵억제 실증","description":"상황보고: 조선인민군 전략군이 화성-18형 ICBM 1기를 최대 사거리 궤도로 발사하여 북태평양 공해상에 낙하시켰다. 사전 통보 없이 진행되었다. 미국 NORAD와 한국 합참이 동시 추적을 확인하였다.\n\n정보평가: 핵전쟁억제력 과시를 위한 정치적 신호로 판단된다. 발사 타이밍은 한미 연합훈련 종료 48시간 후로 설정되었다.","threat_level":"High","affected_regions":["조선민주주의인민공화국","동해","북태평양","괌"],"player_options":[{"id":1,"label":"성명 발표","description":"최고인민회의 명의로 억제력 완성 공식 선언 — 국내 결속 강화"},{"id":2,"label":"추가 발사 대기","description":"적대세력의 반응 관찰 후 후속 조치 결정 — 전략적 유연성 유지"},{"id":3,"label":"중국 통보","description":"베이징에 사전 통보 — 동맹 관계 관리, 압박 완충"},{"id":4,"label":"협상 신호 발신","description":"미국에 조건부 대화 의향 전달 — 제재 완화 가능성 타진"}],"comms":[{"origin":"미국","native_text":"USFK FLASH: DPRK ICBM launch detected. Tracking nominal. No threat to CONUS. ROK/Japan allies notified. Emergency NSC convened.","english_translation":"주한미군 긴급: 북한 ICBM 발사 탐지. 추적 정상. 본토 위협 없음. 한일 동맹국 통보. 긴급 NSC 소집.","priority":"Flash"},{"origin":"조선중앙통신","native_text":"조선중앙통신: 경애하는 최고령도자 동지의 명령에 따라 국가핵무력의 억제력을 실증하는 화성-18형 발사훈련이 성공적으로 진행되었다.","english_translation":"KCNA: Under the Supreme Leader's order, the Hwasong-18 test-fire demonstrating national nuclear deterrence was successfully conducted.","priority":"Immediate"}]}"#,

    r#"{"title":"SANCTION PRESSURE POINT","description":"SITREP: UN Panel of Experts documented DPRK cryptocurrency theft operations netting $1.7 billion USD in 18 months — assessed as financing the ICBM programme. US Treasury designated three exchanges. China and Russia blocked further UN sanctions.\n\nINTELLIGENCE ASSESSMENT: Economic pressure is intensifying but not yet critical. Pyongyang has adapted to previous sanctions through creative evasion. Ship-to-ship fuel transfers continue in international waters.","threat_level":"Medium","affected_regions":["Pyongyang","Yellow Sea","Vladivostok","Cryptocurrency Networks"],"player_options":[{"id":1,"label":"Accelerate Cyber Operations","description":"Intensify cryptocurrency theft programme — maximum revenue within existing capability"},{"id":2,"label":"Request Chinese Buffer","description":"Through back-channels ask Beijing to ease sanctions pressure — tests alliance durability"},{"id":3,"label":"Engage South Korea Informally","description":"Send low-level signal via Track 2 — tests Seoul's appetite for economic engagement"},{"id":4,"label":"Demonstrate Capability","description":"Announce partial nuclear test moratorium — potential sanctions relief in exchange"}],"comms":[{"origin":"USA","native_text":"Treasury OFAC: Additional DPRK-linked entities designated. All jurisdictions must cease transactions or face secondary sanctions.","english_translation":"미 재무부: 추가 북한 연계 기관 지정. 모든 국가는 거래 중단 또는 2차 제재 직면.","priority":"Priority"},{"origin":"China","native_text":"外交部：中方一贯反对单边制裁，呼吁各方以对话协商方式解决朝鲜半岛问题，维护地区和平稳定。","english_translation":"MFA China: China opposes unilateral sanctions and calls for dialogue to resolve the Korean Peninsula issue.","priority":"Priority"}]}"#,
];

const STUBS: &[&str] = &[
    r#"{"title":"ARCTIC FLASHPOINT","description":"SITREP: Russian Northern Fleet has deployed three Borei-class SSBNs to patrol positions under the Arctic ice shelf. NATO SOSUS arrays detected abnormal submarine activity near the GIUK gap. Norwegian coastal radar reports unidentified surface contacts heading southwest.\n\nINTELLIGENCE ASSESSMENT: This deployment exceeds normal rotation patterns. Coincides with Russian suspension of the New START inspection regime. DEFCON advisory recommends heightened ASW readiness across Atlantic Command.","threat_level":"High","affected_regions":["Arctic Ocean","Norwegian Sea","GIUK Gap","Barents Sea"],"player_options":[{"id":1,"label":"Deploy P-8 Poseidon ASW","description":"Send maritime patrol aircraft to track submarine movements — reveals positions but escalates tensions"},{"id":2,"label":"Activate NATO Article 4","description":"Convene emergency consultations — diplomatic but slow"},{"id":3,"label":"Open diplomatic back-channel","description":"Contact Russian MoD directly — risks appearing weak but may defuse"},{"id":4,"label":"Increase DEFCON readiness","description":"Raise alert level — sends strong signal but narrows de-escalation window"}],"comms":[{"origin":"Russia","native_text":"Министерство обороны сообщает: плановые учения Северного флота проходят в штатном режиме. Иностранным судам рекомендовано покинуть зону учений.","english_translation":"Ministry of Defense reports: planned Northern Fleet exercises proceeding normally. Foreign vessels advised to leave exercise zone.","priority":"Priority"},{"origin":"NATO","native_text":"ALLIED MARITIME COMMAND: SIGINT confirms three SSBN departures from Gadzhiyevo. Tracking assets repositioning.","english_translation":"ALLIED MARITIME COMMAND: SIGINT confirms three SSBN departures from Gadzhiyevo. Tracking assets repositioning.","priority":"Immediate"}]}"#,

    r#"{"title":"DRAGON'S REACH","description":"SITREP: PLA Navy carrier group Shandong has entered disputed waters near the Second Island Chain. Satellite imagery confirms J-35 stealth fighters conducting launch operations. Simultaneously, PLA Rocket Force has activated mobile TEL launchers in Fujian province — DF-21D anti-ship ballistic missiles now in pre-launch configuration.\n\nINTELLIGENCE ASSESSMENT: Activity correlates with diplomatic breakdown at the ASEAN Regional Forum. Taiwan has raised its military readiness to Level 2. Japan has scrambled F-35s from Kadena.","threat_level":"Critical","affected_regions":["Taiwan Strait","South China Sea","Fujian Province","Okinawa"],"player_options":[{"id":1,"label":"Reposition 7th Fleet","description":"Move carrier group to Philippine Sea — show of force, high escalation risk"},{"id":2,"label":"UN Security Council session","description":"Push for emergency session — China will likely veto but creates diplomatic record"},{"id":3,"label":"Back-channel Beijing","description":"Engage PRC foreign ministry through unofficial channels — preserves deniability"},{"id":4,"label":"Share intelligence with allies","description":"Brief Japan, Australia, Philippines on PLA movements — builds coalition but risks leak"}],"comms":[{"origin":"China","native_text":"中央军委通告：中国人民解放军海军在本国领海范围内进行例行训练，任何外部势力不得干涉中国内政。","english_translation":"Central Military Commission announces: PLA Navy conducting routine training within sovereign waters. External forces must not interfere in China's internal affairs.","priority":"Flash"},{"origin":"USA","native_text":"PACOM FLASH: Carrier Strike Group Five repositioning per OPLAN contingency. All units condition REDCON-2.","english_translation":"PACOM FLASH: Carrier Strike Group Five repositioning per OPLAN contingency. All units condition REDCON-2.","priority":"Flash"}]}"#,

    r#"{"title":"GHOST CIRCUIT","description":"SITREP: Coordinated cyber intrusion detected across NATO member power grids. Malware signature matches SANDWORM APT group. Estonia, Poland, and Germany reporting rolling blackouts affecting military installations. USCYBERCOM has traced command-and-control servers to infrastructure in Belarus.\n\nINTELLIGENCE ASSESSMENT: Attack pattern suggests pre-positioning for larger operation. Similar TTPs preceded the 2015 Ukraine grid attack. No kinetic military movements detected — this may be a standalone operation or a precursor.","threat_level":"High","affected_regions":["Estonia","Poland","Germany","Belarus"],"player_options":[{"id":1,"label":"Counter-cyber operation","description":"Authorize USCYBERCOM to neutralize C2 servers — effective but crosses cyber-warfare threshold"},{"id":2,"label":"NATO Article 5 debate","description":"Invoke collective defense clause for cyber attack — unprecedented, sets major precedent"},{"id":3,"label":"Diplomatic demarche","description":"Formal protest to Belarus and Russia — conventional response, limited deterrent effect"},{"id":4,"label":"Isolate affected networks","description":"Defensive posture only — contains damage but adversary retains initiative"}],"comms":[{"origin":"Russia","native_text":"Кремль передаёт: Российская Федерация категорически отрицает причастность к кибератакам на инфраструктуру стран НАТО.","english_translation":"Kremlin transmits: Russian Federation categorically denies involvement in cyber attacks on NATO infrastructure.","priority":"Immediate"},{"origin":"NATO","native_text":"SHAPE CYBER OPS: Threat level SUBSTANTIAL. All member states activate national cyber defense protocols immediately.","english_translation":"SHAPE CYBER OPS: Threat level SUBSTANTIAL. All member states activate national cyber defense protocols immediately.","priority":"Immediate"}]}"#,

    r#"{"title":"BROKEN ARROW","description":"SITREP: NORAD early warning satellites detected a thermal bloom over the Kapustin Yar test range consistent with an ICBM launch. Trajectory analysis indicates the missile is on a sub-orbital test trajectory terminating in the Kamchatka impact zone. However, no prior notification was provided through established deconfliction channels.\n\nINTELLIGENCE ASSESSMENT: Russia has conducted unannounced missile tests before, but never during a period of elevated tensions. The lack of prior notification violates the Hague Code of Conduct. STRATCOM is tracking the object and has not classified it as a threat — yet.","threat_level":"Critical","affected_regions":["Kapustin Yar","Kamchatka","Pacific Ocean","CONUS"],"player_options":[{"id":1,"label":"Contact Moscow on hotline","description":"Direct leader-to-leader communication — fastest de-escalation path"},{"id":2,"label":"Raise DEFCON to 3","description":"Prudent military response — signals seriousness without overreaction"},{"id":3,"label":"Scramble B-2 bombers","description":"Visible deterrent signal — extremely escalatory"},{"id":4,"label":"Monitor and assess","description":"Wait for more data — risks appearing passive but avoids premature escalation"}],"comms":[{"origin":"Russia","native_text":"Министерство обороны сообщает: запуск баллистической ракеты произведён в рамках плановых испытаний. Угрозы для иностранных государств нет.","english_translation":"Ministry of Defense reports: ballistic missile launch conducted as part of planned tests. No threat to foreign states.","priority":"Flash"},{"origin":"USA","native_text":"STRATCOM OPREP-3: PINNACLE event. Unannounced Russian ICBM test detected. Tracking nominal. No threat assessment at this time.","english_translation":"STRATCOM OPREP-3: PINNACLE event. Unannounced Russian ICBM test detected. Tracking nominal. No threat assessment at this time.","priority":"Flash"}]}"#,

    r#"{"title":"IRON CURTAIN 2.0","description":"SITREP: Multiple NATO member states report GPS spoofing affecting military and civilian aircraft across the Baltic region. Simultaneously, Russia has announced closure of international airspace over Kaliningrad for 'military exercises' — effectively creating an air corridor denial zone between NATO's eastern flank.\n\nINTELLIGENCE ASSESSMENT: GPS disruption originates from electronic warfare systems deployed in Kaliningrad. Pattern matches Krasukha-4 jamming capability. Combined with airspace closure, this creates a de facto A2/AD bubble threatening NATO's ability to reinforce Baltic states.","threat_level":"Medium","affected_regions":["Baltic Sea","Kaliningrad","Lithuania","Latvia","Estonia"],"player_options":[{"id":1,"label":"Deploy NATO EW assets","description":"Counter-jam Russian systems — technical escalation but restores capability"},{"id":2,"label":"Reroute air traffic","description":"Avoid contested airspace — concedes tactical advantage but avoids incident"},{"id":3,"label":"Formal ICAO complaint","description":"International aviation body protest — slow but legally grounded"},{"id":4,"label":"Enhanced Forward Presence","description":"Surge troops to Baltic states — strong signal but logistically demanding"}],"comms":[{"origin":"Russia","native_text":"Кремль передаёт: временное закрытие воздушного пространства над Калининградской областью — стандартная мера обеспечения безопасности учений.","english_translation":"Kremlin transmits: temporary airspace closure over Kaliningrad Oblast is a standard exercise safety measure.","priority":"Priority"},{"origin":"NATO","native_text":"ALLIED AIR COMMAND: GPS degradation confirmed across Baltics. All aircraft switch to INS backup navigation. Avoid Kaliningrad FIR.","english_translation":"ALLIED AIR COMMAND: GPS degradation confirmed across Baltics. All aircraft switch to INS backup navigation. Avoid Kaliningrad FIR.","priority":"Immediate"}]}"#,

    r#"{"title":"SILK ROAD SEVERANCE","description":"SITREP: Intelligence reports indicate coordinated economic warfare targeting NATO supply chains. Chinese state-linked firms have simultaneously restricted rare earth mineral exports, while Russian energy company Gazprom announced 'maintenance shutdowns' on three major European gas pipelines. Global semiconductor production faces 60-day disruption.\n\nINTELLIGENCE ASSESSMENT: Coordinated timing suggests pre-planned economic pressure campaign. European energy reserves at 40% capacity. Defense industrial base reports critical shortages in guidance system components.","threat_level":"Medium","affected_regions":["European Union","Pacific Rim","Global Supply Chains"],"player_options":[{"id":1,"label":"Invoke emergency stockpiles","description":"Release strategic reserves — buys 90 days but depletes buffer"},{"id":2,"label":"Economic counter-sanctions","description":"Target Russian and Chinese financial systems — mutual economic damage"},{"id":3,"label":"Emergency allied summit","description":"Coordinate response with G7 — unified front but delays action"},{"id":4,"label":"Accelerate domestic production","description":"Fast-track reshoring initiatives — long-term fix, no short-term relief"}],"comms":[{"origin":"China","native_text":"北京指挥部报告：稀土出口管制属于正常贸易政策调整，不针对任何特定国家。","english_translation":"Beijing Command reports: rare earth export controls are normal trade policy adjustments, not targeting any specific country.","priority":"Priority"},{"origin":"NATO","native_text":"ALLIED COMMAND TRANSFORMATION: Supply chain disruption assessment — CRITICAL. Recommend immediate activation of resilience protocols.","english_translation":"ALLIED COMMAND TRANSFORMATION: Supply chain disruption assessment — CRITICAL. Recommend immediate activation of resilience protocols.","priority":"Immediate"}]}"#,
];
